<?php
// $Id$
/**
 * Define some plugin systems to test ctools plugin includes.
 */

/**
 * Implementation of hook_ctools_plugin_dierctory()
 */
function ctools_plugin_test_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools_plugin_test') {
    return 'plugins/' . $plugin;
  }
}

/**
 * CTools plugin information callback for an api with extra defaults.
 *
 * @return
 * Ctools plugin definition array.
 */
function ctools_plugin_test_ctools_plugin_extra_defaults() {
  return array(
    'defaults' => array(
      'bool' => true,
      'string' => 'string',
      'array' => array('some value'),
    ),
  );
}

function ctools_plugin_test_ctools_plugin_cached() {
  return array(
    'cache' => TRUE,
  );
}

function ctools_plugin_test_ctools_plugin_cached_hook() {
  return array(
    'cache' => TRUE,
    'use hooks' => TRUE,
  );
}

function ctools_plugin_test_ctools_plugin_not_cached_hook() {
  return array(
    'cache' => FALSE,
    'use hooks' => TRUE,
  );
}

function ctools_plugin_test_ctools_plugin_test_not_cached_hook() {
  return array(
    'test1' => array(
      'function' => 'ctools_plugin_test_hook_not_cached_test',
      'class' => 'class1',
    ),
  );
}

function ctools_plugin_test_ctools_plugin_test_cached_hook() {
  return array(
    'test1' => array(
      'function' => 'ctools_plugin_test_hook_cached_test',
      'handler' => 'class1',
    ),
  );
}

function ctools_plugin_test_hook_not_cached_test() {}
function ctools_plugin_test_hook_cached_test() {}
