<?php
// $Id$

/**
 * @file
 * Stylizer module
 *
 * This module allows styles to be created and managed on behalf of modules
 * that implement styles.
 *
 * The Stylizer tool allows recolorable styles to be created via a miniature
 * scripting language. Panels utilizes this to allow administrators to add
 * styles directly to any panel display.
 */

/**
 * Implementation of hook_perm()
 */
function stylizer_perm() {
  return array(
    'administer stylizer',
  );
}

/**
 * Implementation of hook_ctools_plugin_directory() to let the system know
 * we implement task and task_handler plugins.
 */
function stylizer_ctools_plugin_directory($module, $plugin) {
  // Most of this module is implemented as an export ui plugin, and the
  // rest is in ctools/includes/stylizer.inc
  if ($module == 'ctools' && $plugin == 'export_ui') {
    return 'plugins/' . $plugin;
  }
}
