<?php
// $Id$

/**
 * @file
 * ctools_custom_content module
 *
 * This module allows styles to be created and managed on behalf of modules
 * that implement styles.
 *
 * The ctools_custom_content tool allows recolorable styles to be created via a miniature
 * scripting language. Panels utilizes this to allow administrators to add
 * styles directly to any panel display.
 */

/**
 * Implementation of hook_perm()
 */
function ctools_custom_content_perm() {
  return array(
    'administer custom content',
  );
}

/**
 * Implementation of hook_ctools_plugin_directory() to let the system know
 * we implement task and task_handler plugins.
 */
function ctools_custom_content_ctools_plugin_directory($module, $plugin) {
  // Most of this module is implemented as an export ui plugin, and the
  // rest is in ctools/includes/ctools_custom_content.inc
  if ($module == 'ctools' && $plugin == 'export_ui') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Create callback for creating a new CTools custom content type.
 *
 * This ensures we get proper defaults from the plugin for its settings.
 */
function ctools_content_type_new($set_defaults) {
  $item = ctools_export_new_object('ctools_custom_content', $set_defaults);
  ctools_include('content');
  $plugin = ctools_get_content_type('custom');
  $item->settings = ctools_content_get_defaults($plugin, array());
  return $item;
}