<?php

function bulk_export_perm() {
  return array('use bulk exporter');
}

function bulk_export_theme() {
  return array('bulk_export_export_form' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

function bulk_export_menu() {
  $items['admin/build/bulkexport'] = array(
    'title' => 'Bulk Exporter',
    'description' => 'Bulk-export multiple CTools-handled data objects to code.',
    'access arguments' => array('use bulk exporter'),
    'page callback' => 'bulk_export_export',
  );
  $items['admin/build/bulkexport/results'] = array(
    'access arguments' => array('use bulk exporter'),
    'page callback' => 'bulk_export_export',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * FAPI gateway to the bulk exporter.
 */
function bulk_export_export() {
  ctools_include('export');
  $schemas = ctools_export_get_schemas(TRUE);
  $exportables = $export_tables = array();

  foreach ($schemas as $table => $schema) {
    if (function_exists($schema['export']['list callback'])) {
      $exportables[$table] = $schema['export']['list callback']();
      $export_tables[$table] = $schema['module'];
    }
  }
  if ($exportables) {
    ctools_include('form');
    $form_state = array(
      're_render' => FALSE,
      'no_redirect' => TRUE,
      'exportables' => $exportables,
      'export_tables' => $export_tables,
    );
    $output = ctools_build_form('bulk_export_export_form', $form_state);
    if (!$output) {
      $output = drupal_get_form('ctools_export_form', $form_state['code'], 'Bulk Export');
    }
    return $output;
  }
  else {
    return t('There are no objects to be exported at this time.');
  }
}

/**
 * FAPI definition for the bulk exporter form.
 *
 */
function bulk_export_export_form(&$form_state) {
  $form = array();
  $form['tables'] = array(
    '#prefix' => '<div class="clear-block">',
    '#suffix' => '</div>',
    '#tree' => TRUE,
  );

  foreach ($form_state['exportables'] as $table => $list) {
    $form['tables'][$table] = array(
      '#type' => 'checkboxes',
      '#options' => $list,
      '#default_value' => array(),
    );
  }

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Module name'),
    '#description' => t('Enter the module name to export code to.'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Export'),
  );

  $form['#action'] = url('admin/build/bulkexport/results');
  $form['#exportables'] = $form_state['exportables'];
  $form['#export_tables'] = $form_state['export_tables'];
  return $form;
}

function theme_bulk_export_export_form($form) {
  $files = module_rebuild_cache();
  $exportables = $form['#exportables'];
  $export_tables = $form['#export_tables'];
  $output = '';

  foreach ($export_tables as $table => $module) {
    $header = array(theme('table_select_header_cell'), "{$files[$module]->info['name']}: $table");
    $rows = array();
    foreach ($exportables[$table] as $name => $title) {
      // $title = $form['tables'][$table][$name]['#title'];
      unset($form['tables'][$table][$name]['#title']);
      $rows[] = array(drupal_render($form['tables'][$table][$name]), $title);
    }
    $output .= '<div class="export-container">';
    $output .= theme('table', $header, $rows);
    $output .= "</div>\n";
  }
  drupal_add_css(drupal_get_path('module', 'bulk_export') . '/bulk_export.css');
  $output .= drupal_render($form);
  return $output;
}

function bulk_export_export_form_submit($form, &$form_state) {
  $code = '';
  $name = empty($form_state['values']['name']) ? 'foo' : $form_state['values']['name'];

  foreach ($form_state['values']['tables'] as $table => $names) {
    array_filter($names);
    if (!empty($names)) {
      $code .= ctools_export_to_hook_code($table, $names, $name) . "\n";
    }
  }
  $form_state['code'] = $code;
}
